services:
  - type: web
    name: skivori-game-backend
    runtime: node
    rootDir: skivori-game-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production